runtime: nodejs22
service: default

env_variables:
  NODE_ENV: "production"
  DATABASE_URL: "mysql://root:IA|8ciHi)sFGhE0y@unix(/cloudsql/hardy-being-469601-g3:us-central1:root)/gowizlyapp_db"

automatic_scaling:
  min_instances: 0
  max_instances: 2

beta_settings:
  cloud_sql_instances: hardy-being-469601-g3:us-central1:root
